// <auto-generated />
namespace FlightTickets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Inital_Setup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inital_Setup));
        
        string IMigrationMetadata.Id
        {
            get { return "202012141353220_Inital_Setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
