// <auto-generated />
namespace FlightTickets.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FirstName_LastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstName_LastName));
        
        string IMigrationMetadata.Id
        {
            get { return "202012160931334_FirstName_LastName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
